// C:\Users\Mubeen\Desktop\psp\js\services\CuratedGames.js

// This is the definitive, pre-searched list of curated games.
// Each category includes a link to the original Backloggd list and an
// array of game objects with their precise title and RAWG API slug.
export const curatedGames = {
    "HACK N SLASH": {
        link: "https://www.backloggd.com/u/boyxmashle/list/hack-n-slash-games-on-psp/",
        games: [
            { title: "Dante's Inferno", slug: "dantes-inferno-psp" },
            { title: "God of War: Ghost of Sparta", slug: "god-of-war-ghost-of-sparta" },
            { title: "God of War: Chains of Olympus", slug: "god-of-war-chains-of-olympus" },
            { title: "Star Wars: The Force Unleashed", slug: "star-wars-the-force-unleashed-psp" },
            { title: "Ghost Rider", slug: "ghost-rider" },
            { title: "Warriors Orochi 2", slug: "warriors-orochi-2" },
            { title: "Strider 2", slug: "strider-2" }
        ]
    },
    "BEAT EM UP": {
        link: "https://www.backloggd.com/u/boyxmashle/list/beat-em-up-games-on-psp/",
        games: [
            { title: "The Warriors", slug: "the-warriors" },
            { title: "Kurohyou: Ryuu ga Gotoku Shinshou", slug: "kurohyou-ryuu-ga-gotoku-shinshou" },
            { title: "Kurohyou 2: Ryuu ga Gotoku Ashura-hen", slug: "kurohyou-2-ryuu-ga-gotoku-ashura-hen" },
            { title: "Guilty Gear Judgment", slug: "guilty-gear-judgment" },
            { title: "Naruto Shippuden: Ultimate Ninja Impact", slug: "naruto-shippuden-ultimate-ninja-impact" },
            { title: "Final Fight", slug: "final-fight" },
            { title: "Knights of the Round", slug: "knights-of-the-round" },
            { title: "The King of Dragons", slug: "the-king-of-dragons" },
            { title: "Captain Commando", slug: "captain-commando" },
            { title: "Top Hunter: Roddy & Cathy", slug: "top-hunter-roddy-cathy" },
            { title: "Comix Zone", slug: "comix-zone" },
            { title: "Kenka Bancho: Badass Rumble", slug: "kenka-bancho-badass-rumble" },
            { title: "Beats of Rage", slug: "beats-of-rage" },
            { title: "Panzer Bandit", slug: "panzer-bandit" },
            { title: "Tenchi wo Kurau II", slug: "tenchi-wo-kurau-ii" }
        ]
    },
    "FIRST PERSON SHOOTER": {
        link: "https://www.backloggd.com/u/boyxmashle/list/fps-games-on-psp/",
        games: [
            { title: "Coded Arms Contagion", slug: "coded-arms-contagion" },
            { title: "Half-Life", slug: "half-life" },
            { title: "Duke Nukem 3D", slug: "duke-nukem-3d" },
            { title: "Shadow Warrior", slug: "shadow-warrior-1997" },
            { title: "Heretic", slug: "heretic" },
            { title: "Hexen", slug: "hexen-beyond-heretic" },
            { title: "Quake", slug: "quake" },
            { title: "Nazi Zombies: Portable", slug: "nazi-zombies-portable" },
            { title: "Doom", slug: "doom-1993" },
            { title: "Doom II", slug: "doom-ii-hell-on-earth" },
            { title: "Wolfenstein 3D", slug: "wolfenstein-3d" },
            { title: "Final Doom", slug: "final-doom" },
            { title: "Alien Resurrection", slug: "alien-resurrection" },
            { title: "Strife", slug: "strife" }
        ]
    },
    "THIRD PERSON SHOOTER": {
        link: "https://www.backloggd.com/u/boyxmashle/list/third-person-shooter-games-on-psp/",
        games: [
            { title: "Star Wars: Battlefront II", slug: "star-wars-battlefront-ii-2005" },
            { title: "The 3rd Birthday", slug: "the-3rd-birthday" },
            { title: "Resistance: Retribution", slug: "resistance-retribution" },
            { title: "Pursuit Force: Extreme Justice", slug: "pursuit-force-extreme-justice" },
            { title: "Syphon Filter: Dark Mirror", slug: "syphon-filter-dark-mirror" },
            { title: "Killzone: Liberation", slug: "killzone-liberation" },
            { title: "Syphon Filter: Logan's Shadow", slug: "syphon-filter-logans-shadow" },
            { title: "Star Wars: Battlefront Elite Squadron", slug: "star-wars-battlefront-elite-squadron" },
            { title: "Chili Con Carnage", slug: "chili-con-carnage" },
            { title: "Ratchet & Clank: Size Matters", slug: "ratchet-clank-size-matters" },
            { title: "Pursuit Force", slug: "pursuit-force" },
            { title: "Miami Vice", slug: "miami-vice-psp" },
            { title: "Armored Core 3 Portable", slug: "armored-core-3-portable" },
            { title: "Armored Core: Silent Line Portable", slug: "armored-core-silent-line-portable" },
            { title: "Armored Core: Last Raven Portable", slug: "armored-core-last-raven-portable" },
            { title: "Mobile Suit Gundam: Gundam vs. Gundam Next Plus", slug: "mobile-suit-gundam-gundam-vs-gundam-next-plus" },
            { title: "Future Cop: LAPD", slug: "future-cop-lapd" },
            { title: "Mega Man Legends", slug: "mega-man-legends" },
            { title: "Mega Man Legends 2", slug: "mega-man-legends-2" },
            { title: "Syphon Filter", slug: "syphon-filter" },
            { title: "Syphon Filter 2", slug: "syphon-filter-2" }
        ]
    },
    "SHOOT EM UP": {
        link: "https://www.backloggd.com/u/boyxmashle/list/shooter-games-on-psp/",
        games: [
            { title: "TwinBee Portable", slug: "twinbee-portable" },
            { title: "Parodius Portable", slug: "parodius-portable" },
            { title: "1941: Counter Attack", slug: "1941-counter-attack" },
            { title: "Dariusburst", slug: "dariusburst" },
            { title: "Salamander Portable", slug: "salamander-portable" },
            { title: "Gradius Collection", slug: "gradius-collection" },
            { title: "Strikers 1945 Plus Portable", slug: "strikers-1945-plus-portable" },
            { title: "Eco Fighters", slug: "eco-fighters" },
            { title: "Cotton: Fantastic Night Dreams", slug: "cotton-fantastic-night-dreams" },
            { title: "R-Type Delta", slug: "r-type-delta" },
            { title: "DoDonPachi", slug: "dodonpachi" },
            { title: "Gunbird", slug: "gunbird" },
            { title: "Harmful Park", slug: "harmful-park" },
            { title: "Einhänder", slug: "einhander" },
            { title: "Darius Gaiden", slug: "darius-gaiden" },
            { title: "In the Hunt", slug: "in-the-hunt" },
            { title: "Omega Boost", slug: "omega-boost" },
            { title: "Soukyuu Gurentai", slug: "soukyuu-gurentai" },
            { title: "Thunder Force V: Perfect System", slug: "thunder-force-v-perfect-system" },
            { title: "Twisted Metal: Head-On", slug: "twisted-metal-head-on" },
            { title: "Forgotten Worlds", slug: "forgotten-worlds" },
            { title: "Last Resort", slug: "last-resort" },
            { title: "Space Invaders '95", slug: "space-invaders-95" },
            { title: "Ginga Ojousama Densetsu Collection", slug: "ginga-ojousama-densetsu-collection" },
            { title: "Soldier Collection", slug: "soldier-collection" },
            { title: "Space Invaders Extreme", slug: "space-invaders-extreme" },
            { title: "G-Darius", slug: "g-darius" },
            { title: "Sonic Wings Special", slug: "sonic-wings-special" },
            { title: "Cotton 100%", slug: "cotton-100" }
        ]
    },
    "RUN N GUN": {
        link: "https://www.backloggd.com/u/boyxmashle/list/run-n-gun-games-on-psp/",
        games: [
            { title: "Metal Slug XX", slug: "metal-slug-xx" },
            { title: "Metal Slug Anthology", slug: "metal-slug-anthology" },
            { title: "The Red Star", slug: "the-red-star" },
            { title: "Shock Troopers", slug: "shock-troopers" },
            { title: "Earthworm Jim 2", slug: "earthworm-jim-2" },
            { title: "Rapid Reload", slug: "rapid-reload" },
            { title: "Rohga: Armor Force", slug: "rohga-armor-force" }
        ]
    },
    "2D PLATFORMER": {
        link: "https://www.backloggd.com/u/boyxmashle/list/2d-platformer-games-on-psp/",
        games: [
            { title: "LittleBigPlanet", slug: "littlebigplanet-psp" },
            { title: "Castlevania: The Dracula X Chronicles", slug: "castlevania-the-dracula-x-chronicles" },
            { title: "Castlevania: Rondo of Blood", slug: "castlevania-rondo-of-blood" },
            { title: "Jetpack Joyride", slug: "jetpack-joyride" },
            { title: "Prinny", slug: "prinny-can-i-really-be-the-hero" },
            { title: "Ultimate Ghosts 'n Goblins", slug: "ultimate-ghosts-n-goblins" },
            { title: "Mega Man Powered Up", slug: "mega-man-powered-up" },
            { title: "Mega Man: Maverick Hunter X", slug: "mega-man-maverick-hunter-x" },
            { title: "Sonic the Hedgehog", slug: "sonic-the-hedgehog" },
            { title: "Sonic the Hedgehog 2", slug: "sonic-the-hedgehog-2" },
            { title: "New Adventure Island", slug: "new-adventure-island" },
            { title: "Ristar", slug: "ristar" },
            { title: "Shinobi III", slug: "shinobi-iii-return-of-the-ninja-master" },
            { title: "VectorMan", slug: "vectorman" },
            { title: "Ghouls 'n Ghosts", slug: "ghouls-n-ghosts" },
            { title: "Mega Twins", slug: "mega-twins" },
            { title: "Canabalt", slug: "canabalt" },
            { title: "Celeste Classic", slug: "celeste-classic" },
            { title: "Super Ghouls'n Ghosts", slug: "super-ghouls-n-ghosts" },
            { title: "Castlevania Chronicles", slug: "castlevania-chronicles" },
            { title: "Rayman", slug: "rayman" },
            { title: "Silhouette Mirage", slug: "silhouette-mirage" },
            { title: "Klonoa: Door to Phantomile", slug: "klonoa-door-to-phantomile" },
            { title: "Mega Man 8", slug: "mega-man-8" },
            { title: "Mega Man X3", slug: "mega-man-x3" },
            { title: "Mega Man X4", slug: "mega-man-x4" },
            { title: "Mega Man X5", slug: "mega-man-x5" },
            { title: "Mega Man X6", slug: "mega-man-x6" },
            { title: "Oddworld: Abe's Oddysee", slug: "oddworld-abes-oddysee" },
            { title: "Oddworld: Abe's Exoddus", slug: "oddworld-abes-exoddus" },
            { title: "The Adventure of Little Ralph", slug: "the-adventure-of-little-ralph" },
            { title: "The Adventures of Lomax", slug: "the-adventures-of-lomax" },
            { title: "Rockman 2", slug: "mega-man-2" },
            { title: "Rockman 3", slug: "mega-man-3" },
            { title: "Rockman 4", slug: "mega-man-4" },
            { title: "Rockman 5", slug: "mega-man-5" },
            { title: "Rockman 6", slug: "mega-man-6" },
            { title: "Umihara Kawase Shun", slug: "umihara-kawase-shun" }
        ]
    },
    "3D PLATFORMER": {
        link: "https://www.backloggd.com/u/boyxmashle/list/3d-platformer-games-on-psp/",
        games: [
            { title: "Daxter", slug: "daxter" },
            { title: "Ratchet & Clank: Size Matters", slug: "ratchet-clank-size-matters" },
            { title: "Kao Challengers", slug: "kao-challengers" },
            { title: "Ape Escape: On the Loose", slug: "ape-escape-on-the-loose" },
            { title: "The Simpsons Game", slug: "the-simpsons-game" },
            { title: "Saru Getchu Saru Saru Daisakusen", slug: "saru-getchu-saru-saru-daisakusen" },
            { title: "Super Mario 64", slug: "super-mario-64" },
            { title: "Rayman 2: The Great Escape", slug: "rayman-2-the-great-escape" },
            { title: "Toy Story 2: Buzz Lightyear to the Rescue!", slug: "toy-story-2-buzz-lightyear-to-the-rescue" },
            { title: "Crash Bandicoot", slug: "crash-bandicoot" },
            { title: "Crash Bandicoot 2: Cortex Strikes Back", slug: "crash-bandicoot-2-cortex-strikes-back" },
            { title: "Crash Bandicoot: Warped", slug: "crash-bandicoot-warped" },
            { title: "Spyro the Dragon", slug: "spyro-the-dragon" },
            { title: "Spyro 2: Ripto's Rage!", slug: "spyro-2-riptos-rage" },
            { title: "Spyro: Year of the Dragon", slug: "spyro-year-of-the-dragon" },
            { title: "Gex 3: Deep Cover Gecko", slug: "gex-3-deep-cover-gecko" }
        ]
    },
    "METROIDVANIA": {
        link: "https://www.backloggd.com/u/boyxmashle/list/metroidvania-games-on-psp/",
        games: [
            { title: "Castlevania: Symphony of the Night", slug: "castlevania-symphony-of-the-night" },
            { title: "Cave Story", slug: "cave-story" },
            { title: "Tomba!", slug: "tomba" },
            { title: "Tomba! 2: The Evil Swine Return", slug: "tomba-2-the-evil-swine-return" }
        ]
    },
    "ROGUELIKE": {
        link: "https://www.backloggd.com/u/boyxmashle/list/roguelike-games-on-psp/",
        games: [
            { title: "Fushigi no Dungeon: Fuurai no Shiren 4 Plus", slug: "fushigi-no-dungeon-fuurai-no-shiren-4-plus" },
            { title: "Z.H.P. Unlosing Ranger vs. Darkdeath Evilman", slug: "zhp-unlosing-ranger-vs-darkdeath-evilman" },
            { title: "Spelunky Classic", slug: "spelunky-classic" },
            { title: "Baroque", slug: "baroque" },
            { title: "Azure Dreams", slug: "azure-dreams" },
            { title: "Chocobo's Dungeon 2", slug: "chocobos-dungeon-2" },
            { title: "World of Dragon Warrior: Torneko The Last Hope", slug: "torneko-the-last-hope" }
        ]
    },
    "RACING": {
        link: "https://www.backloggd.com/u/boyxmashle/list/racing-games-on-psp/",
        games: [
            { title: "MotorStorm: Arctic Edge", slug: "motorstorm-arctic-edge" },
            { title: "Wipeout Pulse", slug: "wipeout-pulse" },
            { title: "Burnout Dominator", slug: "burnout-dominator" },
            { title: "Need for Speed: Carbon - Own the City", slug: "need-for-speed-carbon-own-the-city" },
            { title: "Midnight Club 3: DUB Edition Remix", slug: "midnight-club-3-dub-edition-remix" },
            { title: "OutRun 2006: Coast 2 Coast", slug: "outrun-2006-coast-2-coast" },
            { title: "Gran Turismo", slug: "gran-turismo-psp" },
            { title: "Midnight Club L.A. Remix", slug: "midnight-club-la-remix" },
            { title: "Wipeout Pure", slug: "wipeout-pure" },
            { title: "F1 06", slug: "f1-06" },
            { title: "Burnout Legends", slug: "burnout-legends" },
            { title: "Ridge Racer 2", slug: "ridge-racer-2-psp" },
            { title: "FlatOut: Head On", slug: "flatout-head-on" },
            { title: "Juiced 2: Hot Import Nights", slug: "juiced-2-hot-import-nights" },
            { title: "Crazy Taxi: Fare Wars", slug: "crazy-taxi-fare-wars" },
            { title: "Shrek Smash n' Crash Racing", slug: "shrek-smash-n-crash-racing" },
            { title: "Split/Second", slug: "split-second" },
            { title: "Initial D: Street Stage", slug: "initial-d-street-stage" },
            { title: "Crash Team Racing", slug: "crash-team-racing" },
            { title: "Gran Turismo 2", slug: "gran-turismo-2" },
            { title: "Racing Lagoon", slug: "racing-lagoon" },
            { title: "R4: Ridge Racer Type 4", slug: "r4-ridge-racer-type-4" }
        ]
    },
    "ADVENTURE": {
        link: "https://backloggd.com/u/boyxmashle/list/psp-adventure-games/",
        games: [
            { title: "Shadow of Destiny", slug: "shadow-of-destiny" },
            { title: "B.L.U.E. Legend of Water", slug: "blue-legend-of-water" },
            { title: "Moon: Remix RPG Adventure", slug: "moon-remix-rpg-adventure" },
            { title: "Animetic Story Game 1: Cardcaptor Sakura", slug: "animetic-story-game-1-cardcaptor-sakura" },
            { title: "Zettai Zetsumei Toshi 3: Kowareyuku Machi to Kanojo no Uta", slug: "zettai-zetsumei-toshi-3" },
            { title: "Ecco: The Tides of Time", slug: "ecco-the-tides-of-time" }
        ]
    },
    "SURVIVAL HORROR": {
        link: "https://www.backloggd.com/u/boyxmashle/list/survival-horror-games-on-psp/",
        games: [
            { title: "Silent Hill: Origins", slug: "silent-hill-origins" },
            { title: "Silent Hill: Shattered Memories", slug: "silent-hill-shattered-memories" },
            { title: "ObsCure: The Aftermath", slug: "obscure-the-aftermath" },
            { title: "Corpse Party", slug: "corpse-party" },
            { title: "Silent Hill", slug: "silent-hill" },
            { title: "Dino Crisis", slug: "dino-crisis" },
            { title: "Dino Crisis 2", slug: "dino-crisis-2" },
            { title: "Resident Evil 2", slug: "resident-evil-2-1998" },
            { title: "Resident Evil 3: Nemesis", slug: "resident-evil-3-nemesis" },
            { title: "Hellnight", slug: "hellnight" },
            { title: "Echo Night 2: Nemuri no Shihaisha", slug: "echo-night-2-nemuri-no-shihaisha" },
            { title: "Galerians", slug: "galerians" },
            { title: "Clock Tower: The First Fear", slug: "clock-tower-the-first-fear" },
            { title: "Parasite Eve II", slug: "parasite-eve-ii" },
            { title: "Parasite Eve", slug: "parasite-eve" }
        ]
    },
    "RHYTHM": {
        link: "https://www.backloggd.com/u/boyxmashle/list/rhythm-games-on-psp/",
        games: [
            { title: "Hatsune Miku: Project Diva Extend", slug: "hatsune-miku-project-diva-extend" },
            { title: "Gitaroo Man Lives!", slug: "gitaroo-man-lives" },
            { title: "Taiko no Tatsujin Portable DX", slug: "taiko-no-tatsujin-portable-dx" },
            { title: "PaRappa the Rapper", slug: "parappa-the-rapper" },
            { title: "Patapon 2", slug: "patapon-2" },
            { title: "Patapon 3", slug: "patapon-3" },
            { title: "Patapon", slug: "patapon" },
            { title: "Hatsune Miku: Project Diva 2nd", slug: "hatsune-miku-project-diva-2nd" },
            { title: "DJMax Portable 2", slug: "djmax-portable-2" },
            { title: "Rock Band Unplugged", slug: "rock-band-unplugged" },
            { title: "Um Jammer Lammy", slug: "um-jammer-lammy" },
            { title: "Dance Dance Revolution", slug: "dance-dance-revolution" },
            { title: "Dance Dance Revolution 3rdMix", slug: "dance-dance-revolution-3rdmix" },
            { title: "Friday Night Funkin", slug: "friday-night-funkin" }
        ]
    },
    "VISUAL NOVEL": {
        link: "https://www.backloggd.com/u/boyxmashle/list/visual-novel-games-on-psp/",
        games: [
            { title: "Danganronpa: Trigger Happy Havoc", slug: "danganronpa-trigger-happy-havoc" },
            { title: "Danganronpa 2: Goodbye Despair", slug: "danganronpa-2-goodbye-despair" },
            { title: "Steins;Gate", slug: "steins-gate" },
            { title: "Metal Gear Solid: Digital Graphic Novel", slug: "metal-gear-solid-digital-graphic-novel" },
            { title: "Clannad", slug: "clannad" },
            { title: "Chaos;Head Noah", slug: "chaos-head-noah" },
            { title: "Ever17: The Out of Infinity", slug: "ever17-the-out-of-infinity" },
            { title: "Utawarerumono", slug: "utawarerumono" },
            { title: "Remember11: The Age of Infinity", slug: "remember11-the-age-of-infinity" },
            { title: "428: Shibuya Scramble", slug: "428-shibuya-scramble" },
            { title: "Sweet Fuse: At Your Side", slug: "sweet-fuse-at-your-side" },
            { title: "Doki Doki Literature Club!", slug: "doki-doki-literature-club" },
            { title: "Saya no Uta", slug: "saya-no-uta" },
            { title: "Policenauts", slug: "policenauts" },
            { title: "Snatcher", slug: "snatcher" },
            { title: "Silver Jiken", slug: "silver-jiken" }
        ]
    },
    "SPORTS": {
        link: "https://www.backloggd.com/u/boyxmashle/list/sport-games-on-psp/",
        games: [
            { title: "Pro Evolution Soccer 2013", slug: "pro-evolution-soccer-2013" },
            { title: "Virtua Tennis 3", slug: "virtua-tennis-3" },
            { title: "Tony Hawk's Underground 2 Remix", slug: "tony-hawks-underground-2-remix" },
            { title: "NFL Street 2: Unleashed", slug: "nfl-street-2-unleashed" },
            { title: "SSX on Tour", slug: "ssx-on-tour" },
            { title: "NBA Street Showdown", slug: "nba-street-showdown" },
            { title: "WWE SmackDown! vs. Raw 2006", slug: "wwe-smackdown-vs-raw-2006" },
            { title: "Boxer's Road 2", slug: "boxers-road-2" },
            { title: "Hot Shots Tennis: Get a Grip", slug: "hot-shots-tennis-get-a-grip" },
            { title: "Hot Shots Golf: Open Tee 2", slug: "hot-shots-golf-open-tee-2" },
            { title: "Hajime no Ippo: The Fighting! Portable - Victorious Spirits", slug: "hajime-no-ippo-the-fighting-portable-victorious-spirits" },
            { title: "Neo Turf Masters", slug: "neo-turf-masters" },
            { title: "Baseball Stars 2", slug: "baseball-stars-2" },
            { title: "NHL 07", slug: "nhl-07" },
            { title: "Fight Night Round 3", slug: "fight-night-round-3" },
            { title: "FIFA Street 2", slug: "fifa-street-2" },
            { title: "League Bowling", slug: "league-bowling" },
            { title: "NBA Jam Tournament Edition", slug: "nba-jam-tournament-edition" }
        ]
    },
    "PUZZLE": {
        link: "https://www.backloggd.com/u/boyxmashle/list/puzzle-games-on-psp/",
        games: [
            { title: "Lumines II", slug: "lumines-ii" },
            { title: "Zuma", slug: "zuma" },
            { title: "Pac-Man Championship Edition", slug: "pac-man-championship-edition" },
            { title: "Puyo Puyo!! 20th Anniversary", slug: "puyo-puyo-20th-anniversary" },
            { title: "LocoRoco 2", slug: "locoroco-2" },
            { title: "LocoRoco", slug: "locoroco" },
            { title: "Tetris", slug: "tetris" },
            { title: "Crush", slug: "crush" },
            { title: "Me & My Katamari", slug: "me-my-katamari" },
            { title: "Exit 2", slug: "exit-2" },
            { title: "Quiz & Dragons: Capcom Quiz Game", slug: "quiz-dragons-capcom-quiz-game" },
            { title: "Puzzle Quest: Challenge of the Warlords", slug: "puzzle-quest-challenge-of-the-warlords" },
            { title: "Money Puzzle Exchanger", slug: "money-puzzle-exchanger" },
            { title: "Super Monkey Ball Adventure", slug: "super-monkey-ball-adventure" },
            { title: "Puyo Pop Fever", slug: "puyo-pop-fever" },
            { title: "Bomberman '94", slug: "bomberman-94" },
            { title: "Super Puzzle Fighter II Turbo", slug: "super-puzzle-fighter-ii-turbo" },
            { title: "Mr. Driller", slug: "mr-driller" },
            { title: "Bust-a-Move 4", slug: "bust-a-move-4" },
            { title: "Magical Drop III: Yokubari Tokudaigou!", slug: "magical-drop-iii-yokubari-tokudaigou" },
            { title: "Devil Dice", slug: "devil-dice" },
            { title: "Yoyo's Puzzle Park", slug: "yoyos-puzzle-park" }
        ]
    },
    "SIMULATION": {
        link: "https://www.backloggd.com/u/boyxmashle/list/simulation-games-on-psp/",
        games: [
            { title: "Ace Combat X: Skies of Deception", slug: "ace-combat-x-skies-of-deception" },
            { title: "Boku no Natsuyasumi 4", slug: "boku-no-natsuyasumi-4" },
            { title: "Boku no Natsuyasumi 2", slug: "boku-no-natsuyasumi-2" },
            { title: "Innocent Life: A Futuristic Harvest Moon", slug: "innocent-life-a-futuristic-harvest-moon" },
            { title: "Doko Demo Issho Portable", slug: "doko-demo-issho-portable" },
            { title: "Harvest Moon: Hero of Leaf Valley", slug: "harvest-moon-hero-of-leaf-valley" },
            { title: "Harvest Moon: Boy & Girl", slug: "harvest-moon-boy-girl" },
            { title: "The Sims 2", slug: "the-sims-2-psp" },
            { title: "Doko Demo Issho: Let's Gakkou!", slug: "doko-demo-issho-lets-gakkou" },
            { title: "Princess Maker 5 Portable", slug: "princess-maker-5-portable" },
            { title: "The Sims 2: Pets", slug: "the-sims-2-pets-psp" },
            { title: "The Sims 2: Castaway", slug: "the-sims-2-castaway" },
            { title: "Thrillville: Off the Rails", slug: "thrillville-off-the-rails" },
            { title: "Shepherd's Crossing", slug: "shepherds-crossing" },
            { title: "Haunting Starring Polterguy", slug: "haunting-starring-polterguy" },
            { title: "Transport Tycoon Deluxe", slug: "transport-tycoon-deluxe" },
            { title: "Ace Combat 3: Electrosphere", slug: "ace-combat-3-electrosphere" },
            { title: "Ore no Ryouri", slug: "ore-no-ryouri" }
        ]
    },
    "STEALTH": {
        link: "https://www.backloggd.com/u/boyxmashle/list/stealth-games-on-psp/",
        games: [
            { title: "Metal Gear Solid: Peace Walker", slug: "metal-gear-solid-peace-walker" },
            { title: "Assassin's Creed: Bloodlines", slug: "assassins-creed-bloodlines" },
            { title: "Tenchu 3 Portable", slug: "tenchu-wrath-of-heaven" },
            { title: "Syphon Filter: Dark Mirror", slug: "syphon-filter-dark-mirror" },
            { title: "Manhunt 2", slug: "manhunt-2" },
            { title: "Metal Gear Solid: Portable Ops", slug: "metal-gear-solid-portable-ops" },
            { title: "Metal Gear Solid: Portable Ops Plus", slug: "metal-gear-solid-portable-ops-plus" },
            { title: "Syphon Filter: Logan's Shadow", slug: "syphon-filter-logans-shadow" },
            { title: "Tenchu Kurenai Portable", slug: "tenchu-kurenai-portable" },
            { title: "Metal Gear Solid", slug: "metal-gear-solid" },
            { title: "Tenchu 2: Birth of the Stealth Assassins", slug: "tenchu-2-birth-of-the-stealth-assassins" }
        ]
    },
    "STRATEGY": {
        link: "https://www.backloggd.com/u/boyxmashle/list/strategy-games-on-psp/",
        games: [
            { title: "Knights in the Nightmare", slug: "knights-in-the-nightmare" },
            { title: "PixelJunk Monsters Deluxe", slug: "pixeljunk-monsters-deluxe" },
            { title: "Warhammer 40,000: Squad Command", slug: "warhammer-40000-squad-command" },
            { title: "Metal Gear Acid 2", slug: "metal-gear-acid-2" },
            { title: "Metal Gear Acid", slug: "metal-gear-acid" },
            { title: "Yu-Gi-Oh! ARC-V Tag Force Special", slug: "yu-gi-oh-arc-v-tag-force-special" },
            { title: "Yu-Gi-Oh! GX Tag Force 3", slug: "yu-gi-oh-gx-tag-force-3" },
            { title: "Worms: Open Warfare 2", slug: "worms-open-warfare-2" },
            { title: "Fat Princess: Fistful of Cake", slug: "fat-princess-fistful-of-cake" },
            { title: "Crystal Defenders", slug: "crystal-defenders" },
            { title: "Sid Meier's Pirates!", slug: "sid-meiers-pirates" },
            { title: "Warcraft II: The Dark Saga", slug: "warcraft-ii-the-dark-saga" }
        ]
    },
    "ACTION ADVENTURE": {
        link: "https://backloggd.com/u/boyxmashle/list/action-adventure-games-on-psp/",
        games: [
            { title: "Grand Theft Auto: Liberty City Stories", slug: "grand-theft-auto-liberty-city-stories" },
            { title: "Grand Theft Auto: Chinatown Wars", slug: "grand-theft-auto-chinatown-wars" },
            { title: "Grand Theft Auto: Vice City Stories", slug: "grand-theft-auto-vice-city-stories" },
            { title: "LEGO Batman: The Videogame", slug: "lego-batman-the-videogame" },
            { title: "LEGO Star Wars II: The Original Trilogy", slug: "lego-star-wars-ii-the-original-trilogy" },
            { title: "LEGO Star Wars III: The Clone Wars", slug: "lego-star-wars-iii-the-clone-wars" },
            { title: "LEGO Indiana Jones: The Original Adventures", slug: "lego-indiana-jones-the-original-adventures" },
            { title: "LEGO Harry Potter: Years 5-7", slug: "lego-harry-potter-years-5-7" },
            { title: "LEGO Harry Potter: Years 1-4", slug: "lego-harry-potter-years-1-4" },
            { title: "Tomb Raider: Anniversary", slug: "tomb-raider-anniversary" },
            { title: "Dead Head Fred", slug: "dead-head-fred" },
            { title: "Retro City Rampage DX", slug: "retro-city-rampage-dx" },
            { title: "Toy Story 3", slug: "toy-story-3" },
            { title: "Way of the Samurai Portable 2", slug: "way-of-the-samurai-portable-2" },
            { title: "Way of the Samurai Portable", slug: "way-of-the-samurai-portable" },
            { title: "MediEvil: Resurrection", slug: "medievil-resurrection" },
            { title: "The Legend of Zelda: Oni Link Begins", slug: "the-legend-of-zelda-oni-link-begins" },
            { title: "The Legend of Zelda: Return of the Hylian", slug: "the-legend-of-zelda-return-of-the-hylian" },
            { title: "Alundra", slug: "alundra" },
            { title: "Legacy of Kain: Soul Reaver", slug: "legacy-of-kain-soul-reaver" },
            { title: "The Misadventures of Tron Bonne", slug: "the-misadventures-of-tron-bonne" },
            { title: "The Legend of Valkyrie", slug: "the-legend-of-valkyrie" },
            { title: "Herc's Adventures", slug: "hercs-adventures" },
            { title: "Serial Experiments Lain", slug: "serial-experiments-lain" },
            { title: "Dr. Slump", slug: "dr-slump" },
            { title: "Tail Concerto", slug: "tail-concerto" }
        ]
    },
    "FIGHTING": {
        link: "https://www.backloggd.com/u/boyxmashle/list/fighting-games-on-psp/",
        games: [
            { title: "Tekken 6", slug: "tekken-6" },
            { title: "Street Fighter Alpha 3 MAX", slug: "street-fighter-alpha-3-max" },
            { title: "BlazBlue: Calamity Trigger Portable", slug: "blazblue-calamity-trigger-portable" },
            { title: "SoulCalibur: Broken Destiny", slug: "soulcalibur-broken-destiny" },
            { title: "Def Jam Fight For NY: The Takeover", slug: "def-jam-fight-for-ny-the-takeover" },
            { title: "Guilty Gear XX Accent Core Plus", slug: "guilty-gear-xx-accent-core-plus" },
            { title: "BlazBlue: Continuum Shift Extend", slug: "blazblue-continuum-shift-extend" },
            { title: "Darkstalkers Chronicle: The Chaos Tower", slug: "darkstalkers-chronicle-the-chaos-tower" },
            { title: "Spectral vs. Generation", slug: "spectral-vs-generation" },
            { title: "Samurai Shodown Anthology", slug: "samurai-shodown-anthology" },
            { title: "Tekken: Dark Resurrection", slug: "tekken-dark-resurrection" },
            { title: "Power Stone Collection", slug: "power-stone-collection" },
            { title: "Mortal Kombat: Unchained", slug: "mortal-kombat-unchained" },
            { title: "Naruto: Ultimate Ninja Heroes 2", slug: "naruto-ultimate-ninja-heroes-2" },
            { title: "Dragon Ball Z: Shin Budokai 2", slug: "dragon-ball-z-shin-budokai-2" },
            { title: "The King of Fighters Collection: The Orochi Saga", slug: "the-king-of-fighters-collection-the-orochi-saga" },
            { title: "Dragon Ball Z: Tenkaichi Tag Team", slug: "dragon-ball-z-tenkaichi-tag-team" },
            { title: "Dissidia 012 Final Fantasy", slug: "dissidia-012-duodecim-final-fantasy" },
            { title: "JoJo's Bizarre Adventure", slug: "jojos-bizarre-adventure" },
            { title: "Marvel vs. Capcom: Clash of Super Heroes", slug: "marvel-vs-capcom-clash-of-super-heroes" },
            { title: "Capcom vs. SNK: Millennium Fight 2000 Pro", slug: "capcom-vs-snk-millennium-fight-2000-pro" },
            { title: "Real Bout Fatal Fury Special", slug: "real-bout-fatal-fury-special" },
            { title: "The Last Blade", slug: "the-last-blade" },
            { title: "Rival Schools: United by Fate", slug: "rival-schools-united-by-fate" },
            { title: "Bloody Roar 2", slug: "bloody-roar-2" },
            { title: "X-Men vs. Street Fighter", slug: "x-men-vs-street-fighter" },
            { title: "Gundam Battle Assault 2", slug: "gundam-battle-assault-2" },
            { title: "Shaman King: Spirit of Shamans", slug: "shaman-king-spirit-of-shamans" },
            { title: "Cyberbots: Fullmetal Madness", slug: "cyberbots-fullmetal-madness" },
            { title: "Rakugaki showtime", slug: "rakugaki-showtime" }
        ]
    },
    "ACTION RPG": {
        link: "https://www.backloggd.com/u/boyxmashle/list/action-rpg-games-on-psp/",
        games: [
            { title: "Crisis Core: Final Fantasy VII", slug: "crisis-core-final-fantasy-vii" },
            { title: "Kingdom Hearts Birth by Sleep Final Mix", slug: "kingdom-hearts-birth-by-sleep-final-mix" },
            { title: "Monster Hunter Freedom Unite", slug: "monster-hunter-freedom-unite" },
            { title: "Ys Seven", slug: "ys-seven" },
            { title: "Phantasy Star Portable 2 Infinity", slug: "phantasy-star-portable-2-infinity" },
            { title: "Final Fantasy Type-0", slug: "final-fantasy-type-0" },
            { title: "Monster Hunter Portable 3rd", slug: "monster-hunter-portable-3rd" },
            { title: "Tales of Eternia", slug: "tales-of-eternia" },
            { title: "Nayuta no Kiseki", slug: "nayuta-no-kiseki" },
            { title: "Ys VI: The Ark of Napishtim", slug: "ys-vi-the-ark-of-napishtim" },
            { title: "Toukiden: Kiwami", slug: "toukiden-kiwami" },
            { title: "Half-Minute Hero", slug: "half-minute-hero" },
            { title: "Half-Minute Hero The Second Coming", slug: "half-minute-hero-the-second-coming" },
            { title: "Gurumin: A Monstrous Adventure", slug: "gurumin-a-monstrous-adventure" },
            { title: "Gods Eater Burst", slug: "gods-eater-burst" },
            { title: "God Eater 2", slug: "god-eater-2" },
            { title: "Tales of the World: Radiant Mythology 3", slug: "tales-of-the-world-radiant-mythology-3" },
            { title: "Ys I & II Chronicles", slug: "ys-i-ii-chronicles" },
            { title: "Star Ocean: Second Evolution", slug: "star-ocean-second-evolution" },
            { title: "Ys: The Oath in Felghana", slug: "ys-the-oath-in-felghana" },
            { title: "Star Ocean: First Departure", slug: "star-ocean-first-departure" },
            { title: "Tales of Rebirth", slug: "tales-of-rebirth" },
            { title: "Tales of Destiny 2", slug: "tales-of-destiny-2" },
            { title: "Princess Crown", slug: "princess-crown" },
            { title: "Black Rock Shooter: The Game", slug: "black-rock-shooter-the-game" },
            { title: "Marvel: Ultimate Alliance", slug: "marvel-ultimate-alliance" },
            { title: "Brandish: The Dark Revenant", slug: "brandish-the-dark-revenant" },
            { title: "Parasite Eve", slug: "parasite-eve" },
            { title: "Tales of Destiny", slug: "tales-of-destiny" },
            { title: "Community Pom", slug: "community-pom" },
            { title: "Vagrant Story", slug: "vagrant-story" },
            { title: "Legend of Mana", slug: "legend-of-mana" },
            { title: "Tales of Phantasia", slug: "tales-of-phantasia" },
            { title: "Threads of Fate", slug: "threads-of-fate" },
            { title: "Parasite Eve II", slug: "parasite-eve-ii" },
            { title: "Shadow Tower", slug: "shadow-tower" },
            { title: "Diablo", slug: "diablo" },
            { title: "Brave Prove", slug: "brave-prove" },
            { title: "King's Field II", slug: "kings-field-ii" },
            { title: "Dragon Valor", slug: "dragon-valor" }
        ]
    },
    "TURN BASED RPG": {
        link: "https://www.backloggd.com/u/boyxmashle/list/turn-based-rpg-games-on-psp/",
        games: [
            { title: "Persona 3 Portable", slug: "persona-3-portable" },
            { title: "Valkyrie Profile: Lenneth", slug: "valkyrie-profile-lenneth" },
            { title: "Breath of Fire III", slug: "breath-of-fire-iii" },
            { title: "The Legend of Heroes: Trails in the Sky SC", slug: "the-legend-of-heroes-trails-in-the-sky-sc" },
            { title: "The Legend of Heroes: Trails in the Sky the 3rd", slug: "the-legend-of-heroes-trails-in-the-sky-the-3rd" },
            { title: "The Legend of Heroes: Trails in the Sky", slug: "the-legend-of-heroes-trails-in-the-sky" },
            { title: "The Legend of Heroes: Trails from Zero", slug: "the-legend-of-heroes-trails-from-zero" },
            { title: "Persona 2: Eternal Punishment", slug: "persona-2-eternal-punishment" },
            { title: "Final Fantasy III", slug: "final-fantasy-iii" },
            { title: "Atelier Violet: The Alchemist of Gramnad 2", slug: "atelier-violet-the-alchemist-of-gramnad-2" },
            { title: "The Legend of Heroes: Trails to Azure", slug: "the-legend-of-heroes-trails-to-azure" },
            { title: "Fate Extra CCC", slug: "fate-extra-ccc" },
            { title: "Sol Trigger", slug: "sol-trigger" },
            { title: "Phantasy Star IV: The End of the Millennium", slug: "phantasy-star-iv-the-end-of-the-millennium" },
            { title: "Shin Megami Tensei: Persona", slug: "shin-megami-tensei-persona" },
            { title: "Digimon World Re:Digitize", slug: "digimon-world-re-digitize" },
            { title: "Final Fantasy IV: The Complete Collection", slug: "final-fantasy-iv-the-complete-collection" },
            { title: "Persona 2 - Innocent Sin", slug: "persona-2-innocent-sin" },
            { title: "Fate Extra", slug: "fate-extra" },
            { title: "Riviera: The Promised Land", slug: "riviera-the-promised-land" },
            { title: "Digimon Adventure", slug: "digimon-adventure" },
            { title: "Mana Khemia: Student Alliance", slug: "mana-khemia-student-alliance" },
            { title: "PoPoLoCrois", slug: "popolocrois" },
            { title: "7th Dragon 2020-II", slug: "7th-dragon-2020-ii" },
            { title: "7th Dragon 2020", slug: "7th-dragon-2020" },
            { title: "Lunar 2: Eternal Blue Complete", slug: "lunar-2-eternal-blue-complete" },
            { title: "Breath of Fire IV", slug: "breath-of-fire-iv" },
            { title: "Final Fantasy IX", slug: "final-fantasy-ix" },
            { title: "Final Fantasy VII", slug: "final-fantasy-vii" },
            { title: "Final Fantasy VIII", slug: "final-fantasy-viii" },
            { title: "Final Fantasy VI", slug: "final-fantasy-vi" },
            { title: "Grandia", slug: "grandia" },
            { title: "The Legend of Dragoon", slug: "the-legend-of-dragoon" },
            { title: "Chrono Cross", slug: "chrono-cross" },
            { title: "Chrono Trigger", slug: "chrono-trigger" },
            { title: "Dragon Warrior VII", slug: "dragon-warrior-vii" },
            { title: "Xenogears", slug: "xenogears" },
            { title: "Koudelka", slug: "koudelka" },
            { title: "Suikoden", slug: "suikoden" },
            { title: "Suikoden II", slug: "suikoden-ii" },
            { title: "SaGa Frontier 2", slug: "saga-frontier-2" },
            { title: "SaGa Frontier", slug: "saga-frontier" },
            { title: "Digimon World 3", slug: "digimon-world-3" },
            { title: "Shin Megami Tensei", slug: "shin-megami-tensei" },
            { title: "Lunar: Silver Star Story Complete", slug: "lunar-silver-star-story-complete" },
            { title: "Shin Megami Tensei II", slug: "shin-megami-tensei-ii" },
            { title: "Dragon Quest IV", slug: "dragon-quest-iv" },
            { title: "Dragon Quest Monsters 1+2", slug: "dragon-quest-monsters-1-2" },
            { title: "Shin Megami Tensei: Devil Summoner", slug: "shin-megami-tensei-devil-summoner" },
            { title: "Linda Cube Again", slug: "linda-cube-again" }
        ]
    },
    "TACTICAL RPG": {
        link: "https://www.backloggd.com/u/boyxmashle/list/tactical-rpg-games-on-psp/",
        games: [
            { title: "Jeanne d'Arc", slug: "jeanne-darc" },
            { title: "Tactics Ogre: Let Us Cling Together", slug: "tactics-ogre-let-us-cling-together" },
            { title: "Final Fantasy Tactics: The War of the Lions", slug: "final-fantasy-tactics-the-war-of-the-lions" },
            { title: "Phantom Brave: The Hermuda Triangle", slug: "phantom-brave-the-hermuda-triangle" },
            { title: "Disgaea: Afternoon of Darkness", slug: "disgaea-afternoon-of-darkness" },
            { title: "Valkyria Chronicles 2", slug: "valkyria-chronicles-2" },
            { title: "Valkyria Chronicles 3: Unrecorded Chronicles", slug: "valkyria-chronicles-3-unrecorded-chronicles" },
            { title: "Disgaea 2: Dark Hero Days", slug: "disgaea-2-dark-hero-days" },
            { title: "Grand Knights History", slug: "grand-knights-history" },
            { title: "Growlanser IV: Overreloaded", slug: "growlanser-iv-overreloaded" },
            { title: "Spectral Souls: Resurrection of the Ethereal Empires", slug: "spectral-souls-resurrection-of-the-ethereal-empires" },
            { title: "Wild Arms XF", slug: "wild-arms-xf" },
            { title: "Sakura Taisen 1 & 2", slug: "sakura-taisen-1-2" },
            { title: "Phantom Kingdom: Portable", slug: "phantom-kingdom-portable" },
            { title: "Blazing Souls Accelate", slug: "blazing-souls-accelate" },
            { title: "Summon Night 3", slug: "summon-night-3" },
            { title: "Ragnarok: Tactics", slug: "ragnarok-tactics" },
            { title: "La Pucelle: Ragnarok", slug: "la-pucelle-ragnarok" },
            { title: "Gungnir", slug: "gungnir" },
            { title: "Yggdra Union: We'll Never Fight Alone", slug: "yggdra-union" },
            { title: "Super Robot Taisen A Portable Plus", slug: "super-robot-taisen-a-portable-plus" },
            { title: "Dai-2-ji Super Robot Taisen Z: Saisei-hen", slug: "dai-2-ji-super-robot-taisen-z-saisei-hen" },
            { title: "Dai-2-ji Super Robot Taisen Z: Hakai-hen", slug: "dai-2-ji-super-robot-taisen-z-hakai-hen" },
            { title: "Rhapsody: A Musical Adventure", slug: "rhapsody-a-musical-adventure" },
            { title: "Brigandine: Grand Edition", slug: "brigandine-grand-edition" },
            { title: "Front Mission 3", slug: "front-mission-3" },
            { title: "Front Mission 2", slug: "front-mission-2" },
            { title: "Tear Ring Saga", slug: "tear-ring-saga" },
            { title: "Vandal Hearts", slug: "vandal-hearts" },
            { title: "Vandal Hearts II", slug: "vandal-hearts-ii" },
            { title: "Ogre Battle: The March of the Black Queen", slug: "ogre-battle-the-march-of-the-black-queen" },
            { title: "Vanguard Bandits", slug: "vanguard-bandits" },
            { title: "Super Robot Taisen Alpha Gaiden", slug: "super-robot-taisen-alpha-gaiden" },
            { title: "Langrisser IV", slug: "langrisser-iv" },
            { title: "Arc the Lad II", slug: "arc-the-lad-ii" },
            { title: "Little Princess: Marl Oukoku no Ningyou Hime 2", slug: "little-princess-marl-oukoku-no-ningyou-hime-2" }
        ]
    },
    "COMPILATION": {
        link: "https://www.backloggd.com/u/boyxmashle/list/compilation-games-on-psp/",
        games: [
            { title: "Metal Slug Anthology", slug: "metal-slug-anthology" },
            { title: "Sega Genesis Collection", slug: "sega-genesis-collection" },
            { title: "Castlevania: The Dracula X Chronicles", slug: "castlevania-the-dracula-x-chronicles" },
            { title: "Ys I & II Chronicles", slug: "ys-i-ii-chronicles" },
            { title: "SNK Arcade Classics Vol. 1", slug: "snk-arcade-classics-vol-1" },
            { title: "Power Stone Collection", slug: "power-stone-collection" },
            { title: "Capcom Classics Collection Reloaded", slug: "capcom-classics-collection-reloaded" },
            { title: "Capcom Classics Collection Remixed", slug: "capcom-classics-collection-remixed" },
            { title: "Capcom Puzzle World", slug: "capcom-puzzle-world" },
            { title: "The King of Fighters Collection: The Orochi Saga", slug: "the-king-of-fighters-collection-the-orochi-saga" },
            { title: "Final Fantasy IV: The Complete Collection", slug: "final-fantasy-iv-the-complete-collection" },
            { title: "Namco Museum Battle Collection", slug: "namco-museum-battle-collection" },
            { title: "Midway Arcade Treasures: Extended Play", slug: "midway-arcade-treasures-extended-play" },
            { title: "Gradius Collection", slug: "gradius-collection" },
            { title: "Three Wonders", slug: "three-wonders" },
            { title: "Parodius Portable", slug: "parodius-portable" },
            { title: "TwinBee Portable", slug: "twinbee-portable" },
            { title: "Samurai Shodown Anthology", slug: "samurai-shodown-anthology" },
            { title: "The Idolmaster: Shiny Festa", slug: "the-idolmaster-shiny-festa" },
            { title: "Soldier Collection", slug: "soldier-collection" },
            { title: "Taito Legends Power-Up", slug: "taito-legends-power-up" },
            { title: "Crazy Taxi: Fare Wars", slug: "crazy-taxi-fare-wars" },
            { title: "Tales of Phantasia: Narikiri Dungeon X", slug: "tales-of-phantasia-narikiri-dungeon-x" },
            { title: "EA Replay", slug: "ea-replay" },
            { title: "Space Invaders Pocket", slug: "space-invaders-pocket" },
            { title: "Sakura Taisen 1 & 2", slug: "sakura-taisen-1-2" },
            { title: "Ginga Ojousama Densetsu Collection", slug: "ginga-ojousama-densetsu-collection" }
        ]
    }
};